name: appletdesign
favicon: null
layout_spectrum: 0.47742
typography_spectrum: 0.33755
title: Ã„pplet design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8cfde'
    - '#a1aabf'
    - '#ececec'
    - '#484848'
    - '#676767'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
