name: appletdesign
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8cfde'
    - '#a1aabf'
    - '#ececec'
    - '#484848'
    - '#676767'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
